### ISSUE TITLE
Getting it to work with Froala Editor

### ISSUE THREAD

**Issue by deronsizemore** [Hawkers/triggeredAutocomplete#14]
I've got this working with a textarea which was pretty straight forward. However, I'm going to be using Froala Editor on my site when users leave comments and would love to have the @mentions ability. At the moment, I've been unsuccessful in making it work with Froala. I was hoping someone with more jquery/javascript experience than myself would be able to give me a fix for this?

I've made a JSFiddle here: http://jsfiddle.net/vq6MH/585/

If you un-comment the Froala editor initialization code at the top of the javascript window, it will enable Froala. 

Thanks

**Comment by Hawkers** [comment]
I wrote this for jQuery UI 1.8 and I believe they didn't add contenteditable support until 1.9 for autocompletes.  The problem is this may break at 1.9, so it might require some updates to get it working.  I'd actually like to update this not to require jQuery UI at all at some point.

**Comment by deronsizemore** [comment]
Ok, thanks. Yeah, I tried using jQuery UI 1.9 and it does break it. As for the updates to get working with a later version of jQuery UI, would you be able to give me an idea of where to start? Or would it be a massive overhaul?

thanks!

**Comment by Hawkers** [comment]
It shouldn't be a massive overhaul to get it working with 1.9 as this was developed for 1.8.  I haven't worked on this for a while, so I don't know exactly where to start, but if you do come up with a working update feel free to push it.

**Comment by deronsizemore** [comment]
Will do. thanks.
