### ISSUE TITLE
Changing triggers renders mentions unparsable

### ISSUE THREAD

**Issue by shovon** [Hawkers/triggeredAutocomplete#9]
OK, so let's say the developer of a social networking site were to use `@` for the trigger in version 1.0.0 of their app, and then were to switch to `+`, then all old mentions will no longer be parsed by the new trigger.

This isn't an issue with triggeredAutocomplete, but it is pretty inconvenient for the developers using it.

**Comment by Hawkers** [comment]
I don't know if there is much that can be done about that without over-complicating the code. If that were to happen it wouldn't be very difficult to run a script through all the data converting the format.
